# Generated by Django 3.0.3 on 2020-03-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50, null=True)),
                ('img_url', models.URLField(max_length=2000)),
                ('description', models.CharField(max_length=500)),
                ('img_start', models.URLField(max_length=2000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizResultMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'quiz_result_message',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=50)),
                ('img_url', models.URLField(max_length=2000, null=True)),
                ('sorting_quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
            options={
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('quiz_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizQuestion')),
            ],
            options={
                'db_table': 'quiz_choices',
            },
        ),
    ]
