# Generated by Django 3.0.3 on 2020-03-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'article_types',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('thumbnail', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateField()),
                ('is_main', models.BooleanField(default=False)),
                ('article_types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
