# Generated by Django 3.0.3 on 2020-03-16 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'favourite_sections',
            },
        ),
        migrations.CreateModel(
            name='HouseChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('img', models.URLField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'house_choices',
            },
        ),
        migrations.CreateModel(
            name='HouseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('img_back', models.URLField(null=True)),
                ('img_center', models.URLField(max_length=2000, null=True)),
                ('img_center_frame', models.URLField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'house_questions',
            },
        ),
        migrations.CreateModel(
            name='HouseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'house_results',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(null=True)),
                ('button_text', models.CharField(max_length=50, null=True)),
                ('img_back', models.URLField(max_length=2000, null=True)),
                ('img_icon', models.URLField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'passports',
            },
        ),
        migrations.CreateModel(
            name='WandChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wand_choices',
            },
        ),
        migrations.CreateModel(
            name='WandQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('img_back', models.URLField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'wand_questions',
            },
        ),
        migrations.CreateModel(
            name='WandResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.URLField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'wand_results',
            },
        ),
        migrations.CreateModel(
            name='WandFomula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='describe_question', to='sorting.WandChoice')),
                ('question2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eyes_question', to='sorting.WandChoice')),
                ('question3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bornday_question', to='sorting.WandChoice')),
                ('question4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pride_question', to='sorting.WandChoice')),
                ('question5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_question', to='sorting.WandChoice')),
                ('question6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fear_question', to='sorting.WandChoice')),
                ('question7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefact_question', to='sorting.WandChoice')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorting.WandResult')),
            ],
            options={
                'db_table': 'wand_fomulas',
            },
        ),
        migrations.AddField(
            model_name='wandchoice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorting.WandQuestion'),
        ),
        migrations.CreateModel(
            name='HouseFomula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moonstar_question', to='sorting.HouseChoice')),
                ('question2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_question', to='sorting.HouseChoice')),
                ('question3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toad_question', to='sorting.HouseChoice')),
                ('question4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_question', to='sorting.HouseChoice')),
                ('question5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expect_question', to='sorting.HouseChoice')),
                ('question6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nightmare_question', to='sorting.HouseChoice')),
                ('question7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratherbe_question', to='sorting.HouseChoice')),
                ('question8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openbox_question', to='sorting.HouseChoice')),
                ('question9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftright_question', to='sorting.HouseChoice')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorting.HouseResult')),
            ],
            options={
                'db_table': 'house_fomulas',
            },
        ),
        migrations.AddField(
            model_name='housechoice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorting.HouseQuestion'),
        ),
        migrations.CreateModel(
            name='FavouriteChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorting.FavouriteSection')),
            ],
            options={
                'db_table': 'favourite_choices',
            },
        ),
    ]
