# Generated by Django 3.0.3 on 2020-03-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_icon', models.URLField(null=True)),
                ('img_bg', models.URLField(null=True)),
                ('img_profile', models.URLField(null=True)),
                ('house_result_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorting.HouseResult')),
            ],
            options={
                'db_table': 'passport_houses',
            },
        ),
    ]
