# Generated by Django 3.0.3 on 2020-03-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefomula',
            name='question1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moonstar_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='housefomula',
            name='question2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='housefomula',
            name='question3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toad_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='housefomula',
            name='question4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='housefomula',
            name='question5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expect_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='housefomula',
            name='question6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nightmare_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='housefomula',
            name='question7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratherbe_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='housefomula',
            name='question8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openbox_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='housefomula',
            name='question9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftright_question', to='sorting.HouseChoice'),
        ),
        migrations.AlterField(
            model_name='wandfomula',
            name='question1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='describe_question', to='sorting.WandChoice'),
        ),
        migrations.AlterField(
            model_name='wandfomula',
            name='question2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eyes_question', to='sorting.WandChoice'),
        ),
        migrations.AlterField(
            model_name='wandfomula',
            name='question3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bornday_question', to='sorting.WandChoice'),
        ),
        migrations.AlterField(
            model_name='wandfomula',
            name='question4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pride_question', to='sorting.WandChoice'),
        ),
        migrations.AlterField(
            model_name='wandfomula',
            name='question5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_question', to='sorting.WandChoice'),
        ),
        migrations.AlterField(
            model_name='wandfomula',
            name='question6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fear_question', to='sorting.WandChoice'),
        ),
        migrations.AlterField(
            model_name='wandfomula',
            name='question7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefact_question', to='sorting.WandChoice'),
        ),
    ]
