# Generated by Django 3.0.3 on 2020-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0002_passporthouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passporthouse',
            old_name='house_result_id',
            new_name='house_result',
        ),
        migrations.AlterField(
            model_name='passporthouse',
            name='img_bg',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='passporthouse',
            name='img_icon',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='passporthouse',
            name='img_profile',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
