# Generated by Django 3.0.3 on 2020-03-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorting', '0003_auto_20200319_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passporthouse',
            name='img_icon',
            field=models.URLField(max_length=3000, null=True),
        ),
    ]
